#!/usr/bin/env bash
# ─────────────────────────────────────────────────────────────────────
# build-docs-site.sh
#
# Creates an MkDocs Material site from forward-engineering artifacts.
#
# Usage:
#   ./build-docs-site.sh [--output-dir ./output] [--site-dir ./doc-site] [--title "My Docs"]
#
# Flags:
#   --output-dir   Path to the forward-engineering output directory (default: ./output)
#   --site-dir     Where the built site will be written (default: ./doc-site)
#   --title        Site title shown in the navbar (default: "lumen Docs")
#   --skip-build   Only scaffold; skip the final mkdocs build
#   --clean        Ignored (kept for CLI compatibility)
# ─────────────────────────────────────────────────────────────────────
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PIPELINE_DIR="$(cd "$SCRIPT_DIR/.." && pwd)"

# ── Defaults ────────────────────────────────────────────────────────
OUTPUT_DIR="./output"
SITE_DIR="./doc-site"
SITE_TITLE="lumen Docs"
SKIP_BUILD=false

# ── Parse args ──────────────────────────────────────────────────────
while [[ $# -gt 0 ]]; do
  case "$1" in
    --output-dir)  OUTPUT_DIR="$2";  shift 2 ;;
    --site-dir)    SITE_DIR="$2";    shift 2 ;;
    --title)       SITE_TITLE="$2";  shift 2 ;;
    --skip-build)  SKIP_BUILD=true;  shift   ;;
    --clean)       shift ;;
    *) echo "Unknown flag: $1"; exit 1 ;;
  esac
done

# ── Validate ────────────────────────────────────────────────────────
if [[ ! -d "$OUTPUT_DIR" ]]; then
  echo "ERROR: Output directory '$OUTPUT_DIR' does not exist."
  exit 1
fi

OUTPUT_DIR="$(cd "$OUTPUT_DIR" && pwd)"

# ── Staging dir (cleaned on exit) ───────────────────────────────────
STAGING="$(mktemp -d)"
trap 'rm -rf "$STAGING"' EXIT

DOCS_DIR="$STAGING/docs"
mkdir -p "$DOCS_DIR"

# ── Step 1: Copy artifacts ───────────────────────────────────────────
echo "Step 1/3: Copying forward-engineering artifacts"

for repo_dir in "$OUTPUT_DIR"/*/; do
  [[ -d "$repo_dir" ]] || continue
  repo_name="$(basename "$repo_dir")"
  # Strip timestamp suffix (<name>-YYYYMMDD-HHMMSS → <name>)
  repo_base="$(echo "$repo_name" | sed 's/-[0-9]\{8\}-[0-9]\{6\}$//')"

  for section_dir in "$repo_dir"artifacts/*/; do
    [[ -d "$section_dir" ]] || continue
    section_name="$(basename "$section_dir")"
    [[ "$section_name" == "manifests" ]] && continue

    mkdir -p "$DOCS_DIR/$repo_base/$section_name"
    cp -rp "$section_dir/." "$DOCS_DIR/$repo_base/$section_name/"

    # Wrap .yaml/.yml files in a markdown page so MkDocs includes them in nav
    find "$DOCS_DIR/$repo_base/$section_name" -type f \( -name "*.yaml" -o -name "*.yml" \) | while read -r yaml_file; do
      base="$(basename "$yaml_file" .yaml)"
      base="$(basename "$base" .yml)"
      md_file="$(dirname "$yaml_file")/$base.md"
      title="$(echo "$base" | sed 's/-/ /g' | awk '{for(i=1;i<=NF;i++) $i=toupper(substr($i,1,1)) substr($i,2)}1')"
      printf '# %s\n\n```yaml\n%s\n```\n' "$title" "$(cat "$yaml_file")" > "$md_file"
      rm "$yaml_file"
    done
  done
done

# ── Step 2: Generate index.md ────────────────────────────────────────
echo "Step 2/3: Generating index"

{
  echo "# $SITE_TITLE"
  echo ""
  echo "Auto-generated by [lumen](https://github.com/anthropics/lumen). Select a section from the navigation."
  echo ""

  for repo_dir in "$DOCS_DIR"/*/; do
    [[ -d "$repo_dir" ]] || continue
    repo_name="$(basename "$repo_dir")"
    repo_display="$(echo "$repo_name" | sed 's/-/ /g' | awk '{for(i=1;i<=NF;i++) $i=toupper(substr($i,1,1)) substr($i,2)}1')"
    echo "## $repo_display"
    echo ""
    for section_dir in "$repo_dir"/*/; do
      [[ -d "$section_dir" ]] || continue
      section_name="$(basename "$section_dir")"
      display_name="$(echo "$section_name" | sed 's/-/ /g' | awk '{for(i=1;i<=NF;i++) $i=toupper(substr($i,1,1)) substr($i,2)}1')"
      first_md="$(find "$section_dir" -maxdepth 2 -name "*.md" | sort | head -1)"
      if [[ -n "$first_md" ]]; then
        rel_link="$repo_name/$section_name/$(basename "$first_md")"
        echo "- [$display_name]($rel_link)"
      else
        echo "- **$display_name**"
      fi
    done
    echo ""
  done
} > "$DOCS_DIR/index.md"

# Normalize markdown structure and PlantUML fences before rendering/build.
python3 - "$DOCS_DIR" <<'PY'
from pathlib import Path
import re
import sys

docs_dir = Path(sys.argv[1])
plantuml_pattern = re.compile(r"```plantuml\s*\n(.*?)\n```", re.DOTALL)
bold_heading_then_list = re.compile(
    r"(^\*\*[^*\n]+:?\*\*)\n(?=([-*]|\d+\.)\s)",
    re.MULTILINE,
)

for md_file in docs_dir.rglob("*.md"):
    text = md_file.read_text(encoding="utf-8")
    updated = bold_heading_then_list.sub(r"\1\n\n", text)
    if "```plantuml" in updated:
        updated = plantuml_pattern.sub(lambda m: m.group(1).strip() + "\n", updated)
    if updated == text:
        continue
    md_file.write_text(updated, encoding="utf-8")
PY

HAS_PLANTUML_BLOCKS=false
if grep -R -q '^@startuml' "$DOCS_DIR"; then
  HAS_PLANTUML_BLOCKS=true
fi

if $HAS_PLANTUML_BLOCKS && ! command -v plantuml >/dev/null 2>&1; then
  echo "ERROR: PlantUML diagrams were found in the generated docs, but no local 'plantuml' executable is available."
  echo ""
  echo "To render C4 diagrams correctly, choose one of these paths:"
  echo "  1. Use Docker pipeline/docs mode, which includes PlantUML in the lumen image."
  echo "  2. Install PlantUML locally, then rerun make dev-docs."
  echo ""
  exit 1
fi

if $HAS_PLANTUML_BLOCKS; then
  python3 - "$DOCS_DIR" <<'PY'
from pathlib import Path
import hashlib
import os
import re
import subprocess
import sys

docs_dir = Path(sys.argv[1])
assets_dir = docs_dir / "assets" / "diagrams"
assets_dir.mkdir(parents=True, exist_ok=True)
pattern = re.compile(r"(^|\n)(@startuml.*?@enduml)\s*(?=\n|$)", re.DOTALL)
had_render_failures = False

for md_file in docs_dir.rglob("*.md"):
    text = md_file.read_text(encoding="utf-8")
    if "@startuml" not in text:
        continue

    replacements = []
    for idx, match in enumerate(pattern.finditer(text), start=1):
        block = match.group(2).strip() + "\n"
        digest = hashlib.sha1(f"{md_file.relative_to(docs_dir)}::{idx}::{block}".encode("utf-8")).hexdigest()[:12]
        svg_path = assets_dir / f"{md_file.stem}-{idx}-{digest}.svg"
        result = subprocess.run(
            ["plantuml", "-tsvg", "-pipe"],
            input=block,
            text=True,
            capture_output=True,
            check=False,
        )
        if result.returncode != 0:
            had_render_failures = True
            error = (result.stderr or result.stdout or "Unknown PlantUML error").strip()
            print(
                f"WARN: PlantUML render failed for {md_file.relative_to(docs_dir)} block {idx}: {error}",
                file=sys.stderr,
            )
            fallback = (
                "> Warning: PlantUML rendering failed for this diagram. "
                "Showing source instead.\n\n```text\n"
                + block.rstrip()
                + "\n```\n"
            )
            replacements.append((match.span(2), fallback))
        else:
            svg_path.write_text(result.stdout, encoding="utf-8")
            rel_from_md = Path(os.path.relpath(svg_path, md_file.parent))
            replacements.append((match.span(2), f"![Diagram]({rel_from_md.as_posix()})"))

    if not replacements:
        continue

    updated = text
    for (start, end), replacement in reversed(replacements):
        updated = updated[:start] + replacement + updated[end:]
    md_file.write_text(updated, encoding="utf-8")

if had_render_failures:
    print("WARN: One or more PlantUML blocks failed to render; fallback source blocks were embedded.", file=sys.stderr)
PY
fi

# ── Step 3: Write mkdocs.yml and build ──────────────────────────────
echo "Step 3/3: Building MkDocs Material site"

mkdir -p "$DOCS_DIR/assets/javascripts"
cat > "$DOCS_DIR/assets/javascripts/mermaid-init.js" <<'JS'
document$.subscribe(function () {
  if (typeof mermaid !== "undefined") {
    mermaid.initialize({
      startOnLoad: true,
      securityLevel: "loose",
      theme: "default"
    });
  }
});
JS

cat > "$STAGING/mkdocs.yml" << YAML
site_name: "${SITE_TITLE}"
docs_dir: docs
theme:
  name: material
  palette:
    - scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - scheme: slate
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.top
    - navigation.indexes
    - content.code.copy
    - toc.follow
plugins:
  - search
extra_javascript:
  - https://unpkg.com/mermaid@10/dist/mermaid.min.js
  - assets/javascripts/mermaid-init.js
markdown_extensions:
  - tables
  - attr_list
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
YAML

if $SKIP_BUILD; then
  echo "Skipping build (--skip-build). Staging at: $STAGING"
  trap - EXIT   # don't clean up so caller can inspect
  exit 0
fi

mkdir -p "$(dirname "$SITE_DIR")"
SITE_DIR_ABS="$(cd "$(dirname "$SITE_DIR")" && pwd)/$(basename "$SITE_DIR")"
if command -v uv >/dev/null 2>&1; then
  uv --directory "$PIPELINE_DIR" run mkdocs build -f "$STAGING/mkdocs.yml" --site-dir "$SITE_DIR_ABS"
else
  mkdocs build -f "$STAGING/mkdocs.yml" --site-dir "$SITE_DIR_ABS"
fi

echo ""
echo "Done! Static site at: $SITE_DIR"
echo "Preview with: python -m http.server 8080 --directory $SITE_DIR"
