#!/usr/bin/env bash
# ─────────────────────────────────────────────────────────────────────
# build-docs-site.sh
#
# Creates an MkDocs Material site from forward-engineering artifacts.
#
# Usage:
#   ./build-docs-site.sh [--output-dir ./output] [--site-dir ./doc-site] [--title "My Docs"]
#
# Flags:
#   --output-dir   Path to the forward-engineering output directory (default: ./output)
#   --site-dir     Where the built site will be written (default: ./doc-site)
#   --title        Site title shown in the navbar (default: "lumen Docs")
#   --skip-build   Only scaffold; skip the final mkdocs build
#   --clean        Ignored (kept for CLI compatibility)
# ─────────────────────────────────────────────────────────────────────
set -euo pipefail

# ── Defaults ────────────────────────────────────────────────────────
OUTPUT_DIR="./output"
SITE_DIR="./doc-site"
SITE_TITLE="lumen Docs"
SKIP_BUILD=false

# ── Parse args ──────────────────────────────────────────────────────
while [[ $# -gt 0 ]]; do
  case "$1" in
    --output-dir)  OUTPUT_DIR="$2";  shift 2 ;;
    --site-dir)    SITE_DIR="$2";    shift 2 ;;
    --title)       SITE_TITLE="$2";  shift 2 ;;
    --skip-build)  SKIP_BUILD=true;  shift   ;;
    --clean)       shift ;;
    *) echo "Unknown flag: $1"; exit 1 ;;
  esac
done

# ── Validate ────────────────────────────────────────────────────────
if [[ ! -d "$OUTPUT_DIR" ]]; then
  echo "ERROR: Output directory '$OUTPUT_DIR' does not exist."
  exit 1
fi

OUTPUT_DIR="$(cd "$OUTPUT_DIR" && pwd)"

# ── Staging dir (cleaned on exit) ───────────────────────────────────
STAGING="$(mktemp -d)"
trap 'rm -rf "$STAGING"' EXIT

DOCS_DIR="$STAGING/docs"
mkdir -p "$DOCS_DIR"

# ── Step 1: Copy artifacts ───────────────────────────────────────────
echo "Step 1/3: Copying forward-engineering artifacts"

for repo_dir in "$OUTPUT_DIR"/*/; do
  [[ -d "$repo_dir" ]] || continue
  repo_name="$(basename "$repo_dir")"
  # Strip timestamp suffix (<name>-YYYYMMDD-HHMMSS → <name>)
  repo_base="$(echo "$repo_name" | sed 's/-[0-9]\{8\}-[0-9]\{6\}$//')"

  for section_dir in "$repo_dir"artifacts/*/; do
    [[ -d "$section_dir" ]] || continue
    section_name="$(basename "$section_dir")"
    [[ "$section_name" == "manifests" ]] && continue

    mkdir -p "$DOCS_DIR/$repo_base/$section_name"
    cp -rp "$section_dir/." "$DOCS_DIR/$repo_base/$section_name/"

    # Wrap .yaml/.yml files in a markdown page so MkDocs includes them in nav
    find "$DOCS_DIR/$repo_base/$section_name" -type f \( -name "*.yaml" -o -name "*.yml" \) | while read -r yaml_file; do
      base="$(basename "$yaml_file" .yaml)"
      base="$(basename "$base" .yml)"
      md_file="$(dirname "$yaml_file")/$base.md"
      title="$(echo "$base" | sed 's/-/ /g' | awk '{for(i=1;i<=NF;i++) $i=toupper(substr($i,1,1)) substr($i,2)}1')"
      printf '# %s\n\n```yaml\n%s\n```\n' "$title" "$(cat "$yaml_file")" > "$md_file"
      rm "$yaml_file"
    done
  done
done

# ── Step 2: Generate index.md ────────────────────────────────────────
echo "Step 2/3: Generating index"

{
  echo "# $SITE_TITLE"
  echo ""
  echo "Auto-generated by [lumen](https://github.com/anthropics/lumen). Select a section from the navigation."
  echo ""

  for repo_dir in "$DOCS_DIR"/*/; do
    [[ -d "$repo_dir" ]] || continue
    repo_name="$(basename "$repo_dir")"
    repo_display="$(echo "$repo_name" | sed 's/-/ /g' | awk '{for(i=1;i<=NF;i++) $i=toupper(substr($i,1,1)) substr($i,2)}1')"
    echo "## $repo_display"
    echo ""
    for section_dir in "$repo_dir"/*/; do
      [[ -d "$section_dir" ]] || continue
      section_name="$(basename "$section_dir")"
      display_name="$(echo "$section_name" | sed 's/-/ /g' | awk '{for(i=1;i<=NF;i++) $i=toupper(substr($i,1,1)) substr($i,2)}1')"
      first_md="$(find "$section_dir" -maxdepth 2 -name "*.md" | sort | head -1)"
      if [[ -n "$first_md" ]]; then
        rel_link="$repo_name/$section_name/$(basename "$first_md")"
        echo "- [$display_name]($rel_link)"
      else
        echo "- **$display_name**"
      fi
    done
    echo ""
  done
} > "$DOCS_DIR/index.md"

# ── Step 3: Write mkdocs.yml and build ──────────────────────────────
echo "Step 3/3: Building MkDocs Material site"

cat > "$STAGING/mkdocs.yml" << YAML
site_name: "${SITE_TITLE}"
docs_dir: docs
theme:
  name: material
  palette:
    - scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - scheme: slate
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.top
    - navigation.indexes
    - content.code.copy
    - toc.follow
plugins:
  - search
  - build_plantuml:
      render: "local"
      bin_path: "plantuml"
      output_format: "svg"
      diagram_root: "docs"
      output_folder: "assets/diagrams"
      input_folder: "."
      input_extensions: ""
markdown_extensions:
  - tables
  - attr_list
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.superfences
YAML

if $SKIP_BUILD; then
  echo "Skipping build (--skip-build). Staging at: $STAGING"
  trap - EXIT   # don't clean up so caller can inspect
  exit 0
fi

mkdir -p "$(dirname "$SITE_DIR")"
mkdocs build -f "$STAGING/mkdocs.yml" --site-dir "$(cd "$(dirname "$SITE_DIR")" && pwd)/$(basename "$SITE_DIR")"

echo ""
echo "Done! Static site at: $SITE_DIR"
echo "Preview with: python -m http.server 8080 --directory $SITE_DIR"
